spring:
  datasource:
    url: jdbc:mysql://localhost:3306/enjoytrip?serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  messages:
    basename: messages
    encoding: UTF-8
  sql:
    init:
      mode: always
      schema-locations: classpath:mysql/schema.sql
      data-locations: classpath:mysql/data.sql

mybatis:
  config-location: classpath:/config/mybatis-config.xml

#  C:/Users/dnjsd/enjoytrip/file/
file:
  dir: classpath:/static/images/
