spring:
  application:
    name: enjoytrip

  datasource:
    url: jdbc:mysql://localhost:3306/enjoytrip?serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB

mybatis:
  config-location: classpath:/config/mybatis-config.xml

file:
  dir: C:/Users/SSAFY/enjoytrip-file
