spring:
  datasource:
    url: jdbc:mysql://localhost:3306/enjoytrip?serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: dnjsdud1346@
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 10MB

mybatis:
  config-location: classpath:/config/mybatis-config.xml

#  C:/Users/dnjsd/enjoytrip/file/
file:
  dir: C:/Users/dnjsd/enjoytrip/file/