spring:
  datasource:
    url: jdbc:mysql://localhost:3306/enjoytrip?serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
mybatis:
  config-location: classpath:/config/mybatis-config.xml